# Generated by Django 4.2.7 on 2023-12-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_storage_name_storage_companyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='companyId',
            new_name='company',
        ),
    ]
