# Generated by Django 4.2.7 on 2023-12-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customer_id_alter_customer_user'),
        ('order', '0002_remove_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user.customer'),
            preserve_default=False,
        ),
    ]
