# Generated by Django 4.2.7 on 2023-12-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_productcategory_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
    ]
