# Generated by Django 4.2.7 on 2023-12-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_productcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
