# Generated by Django 4.2.7 on 2023-12-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_adress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adress',
            unique_together={('id', 'title')},
        ),
    ]
