# Generated by Django 4.2.7 on 2023-12-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_adress_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adress',
            unique_together={('customer', 'title')},
        ),
    ]
